;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Anim",DevComment="")
+GameplayTagList=(Tag="Anim.Move",DevComment="")
+GameplayTagList=(Tag="Anim.Move.Idle",DevComment="")
+GameplayTagList=(Tag="Anim.Move.Jog",DevComment="")
+GameplayTagList=(Tag="Anim.Move.Run",DevComment="")
+GameplayTagList=(Tag="Anim.Move.Sprint",DevComment="")
+GameplayTagList=(Tag="Anim.Move.Transition",DevComment="")
+GameplayTagList=(Tag="Anim.Move.Transition.WalkToRun",DevComment="")
+GameplayTagList=(Tag="Anim.Move.Walk",DevComment="")

